ScientificEdition/Areas/Admin/Models/Article/AddArticleToJournalInputModel.cs
using System.ComponentModel.DataAnnotations;

namespace ScientificEdition.Areas.Admin.Models.Article
{
    public class AddArticleToJournalInputModel
    {
        [Required]
        public Guid ArticleId { get; set; }

        [Required]
        public Guid JournalId { get; set; }

        public required Data.Entities.Article Article { get; set; }
    }
}

ScientificEdition/Areas/Admin/Models/Article/ArticleInputModel.cs
using ScientificEdition.Data;
using System.ComponentModel.DataAnnotations;

namespace ScientificEdition.Areas.Admin.Models.Article
{
    public class ArticleInputModel
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Поле обов'язкове.")]
        [StringLength(200, ErrorMessage = "Заголовок не може перевищувати {1} символів.")]
        [Display(Name = "Заголовок")]
        public required string Title { get; set; }

        [Required(ErrorMessage = "Поле обов'язкове.")]
        [Display(Name = "Категорія")]
        public Guid CategoryId { get; set; }

        [Required(ErrorMessage = "Поле обов'язкове.")]
        [Display(Name = "Статус")]
        public ArticleStatus Status { get; set; }

        [Display(Name = "Коментар")]
        public string? Comment { get; set; }
    }
}

ScientificEdition/Areas/Admin/Models/Article/ReviewersAssignmentModel.cs
using ScientificEdition.Mvc.Filters.Validation;
using System.ComponentModel.DataAnnotations;

namespace ScientificEdition.Areas.Admin.Models.Article
{
    public class ReviewersAssignmentModel
    {
        [Required]
        public Guid ArticleId { get; set; }

        public Data.Entities.Article? Article { get; set; }

        [Display(Name = "Доступні рецензенти")]
        [Required]
        [NonEmptyList(2)]
        public List<string> ReviewerIds { get; set; } = [];

        public bool MoveToReview { get; set; }
    }
}

ScientificEdition/Models/Article/ArticleEditViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace ScientificEdition.Models.Article
{
    public class ArticleEditViewModel
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Поле обов'язкове.")]
        [StringLength(200, ErrorMessage = "Заголовок не може перевищувати {1} символів.")]
        [Display(Name = "Заголовок")]
        public required string Title { get; set; }

        [Required(ErrorMessage = "Поле обов'язкове.")]
        [Display(Name = "Категорія")]
        public Guid CategoryId { get; set; }

        [Display(Name = "Коментар")]
        public string? Comment { get; set; }
    }
}

ScientificEdition/Models/Article/ArticleVersionViewModel.cs
using ScientificEdition.Data;

namespace ScientificEdition.Models.Article
{
    public class ArticleVersionViewModel
    {
        public int VersionId { get; set; }

        public int VersionNumber { get; set; }

        public ArticleStatus ArticleStatus { get; set; }

        public DateTime UploadDate { get; set; }

        public string? Comment { get; set; }
    }
}

ScientificEdition/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ScientificEdition.Business;
using ScientificEdition.Data;
using ScientificEdition.Data.Entities;
using ScientificEdition.Models.Article;
using ScientificEdition.Utilities.Files;
using System.Security.Authentication;

namespace ScientificEdition.Controllers
{
    [Authorize(Roles = UserRoles.Author)]
    public class ArticleController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly FileManager fileManager;
        private readonly ArticleManager articleManager;
        private readonly ApplicationDbContext dbContext;

        public ArticleController(
            UserManager<User> userManager,
            FileManager fileManager,
            ArticleManager articleManager,
            ApplicationDbContext context)
        {
            this.userManager = userManager;
            this.fileManager = fileManager;
            this.articleManager = articleManager;
            dbContext = context;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var userId = userManager.GetUserId(User);

            var articles = await dbContext.Articles
                .Where(a => a.AuthorId.Equals(userId))
                .Include(a => a.Author)
                .Include(a => a.Category)
                .Include(a => a.Versions)
                .ThenInclude(v => v.Reviews)
                .Include(a => a.JournalEdition)
                .ToListAsync();

            return View(articles);
        }

        [HttpGet]
        public IActionResult Details(Guid id)
        {
            var article = dbContext.Articles
                .Include(a => a.Category)
                .Include(a => a.Versions)
                .FirstOrDefault(m => m.Id == id);

            if (article == null)
                return NotFound();

            var userId = userManager.GetUserId(User);
            if (User.IsInRole(UserRoles.Author) && article.AuthorId != userId)
                return NotFound();

            article.Versions = article.Versions
                .OrderByDescending(v => v.UploadDate)
                .ToList();

            return View(article);
        }

        [HttpGet]
        public IActionResult VersionDetails(Guid id)
        {
            var version = dbContext.ArticleVersions
                .Include(v => v.Article)
                .Include(v => v.Reviews)
                .FirstOrDefault(v => v.Id == id);

            if (version == null)
                return NotFound();

            var userId = userManager.GetUserId(User);
            if (User.IsInRole(UserRoles.Author) && version.Article!.AuthorId != userId)
                return NotFound();

            return View(version);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpGet]
        public IActionResult DownloadVersion(Guid versionId)
        {
            var version = dbContext.ArticleVersions
                .Include(v => v.Article)
                .FirstOrDefault(v => v.Id == versionId);

            if (version == null)
                return NotFound();

            var userId = userManager.GetUserId(User);
            if (User.IsInRole(UserRoles.Author) && version.Article!.AuthorId != userId)
                return NotFound();

            var filePath = version.FilePath;
            if (!System.IO.File.Exists(filePath))
                return NotFound();

            var articleVersionTitle = $"{version.Article!.Title}_v{version.VersionNumber}";
            var downloadFileName = $"{articleVersionTitle}{Path.GetExtension(filePath)}";

            return PhysicalFile(filePath, "application/octet-stream", downloadFileName);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ArticleInputModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            if (model.File == null || model.File.Length <= 0)
                return View(model);

            var category = await dbContext.Categories.FindAsync(model.CategoryId);
            if (category == null)
                return NotFound();

            var userId = userManager.GetUserId(User);
            if (string.IsNullOrEmpty(userId))
                return NotFound();

            var article = new Article
            {
                Id = Guid.NewGuid(),
                Title = model.Title,
                CategoryId = category.Id,
                UploadDate = DateTime.Now,
                Status = ArticleStatus.New,
                AuthorId = userId
            };
            dbContext.Articles.Add(article);

            var versionNumber = articleManager.GenerateNewArticleVersionNumber(article.Id);
            var filePath = await fileManager.SaveFileAsync(model.File, $"version_{versionNumber}", GetArticleDirectoryPath(article.Id));

            var version = new ArticleVersion
            {
                Id = Guid.NewGuid(),
                VersionNumber = versionNumber,
                ArticleId = article.Id,
                FilePath = filePath,
                Comment = model.Comment,
                UploadDate = article.UploadDate
            };
            dbContext.ArticleVersions.Add(version);

            await dbContext.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private string[] GetArticleDirectoryPath(Guid articleId)
        {
            if (articleId == Guid.Empty)
                throw new ArgumentNullException(nameof(articleId));

            var userId = userManager.GetUserId(User);
            if (string.IsNullOrEmpty(userId))
                throw new AuthenticationException();

            return ["Documents", userId, articleId.ToString()];
        }

        [HttpGet]
        public IActionResult UploadVersion(Guid articleId)
        {
            var article = dbContext.Articles
                .Include(a => a.Versions)
                .FirstOrDefault(a => a.Id == articleId);

            if (article == null)
                return NotFound();

            if (article.Status != ArticleStatus.Rework)
                return BadRequest("Нова версія може бути завантажена тільки для статей у статусі 'На доопрацюванні'.");

            var model = new ArticleVersionInputModel { ArticleId = article.Id };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadVersion(ArticleVersionInputModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var article = dbContext.Articles
                .Include(a => a.Versions)
                .FirstOrDefault(a => a.Id == model.ArticleId);

            if (article == null)
                return NotFound();

            if (article.Status != ArticleStatus.Rework)
                return BadRequest("Нова версія може бути завантажена тільки для статей у статусі 'На доопрацюванні'.");

            var versionNumber = articleManager.GenerateNewArticleVersionNumber(article.Id);
            var filePath = await fileManager.SaveFileAsync(model.File!, $"version_{versionNumber}", GetArticleDirectoryPath(article.Id));

            var version = new ArticleVersion
            {
                Id = Guid.NewGuid(),
                VersionNumber = versionNumber,
                ArticleId = article.Id,
                FilePath = filePath,
                Comment = model.Comment,
                UploadDate = DateTime.Now
            };

            article.Status = ArticleStatus.Review;
            dbContext.ArticleVersions.Add(version);
            dbContext.SaveChanges();

            return RedirectToAction(nameof(Details), new { id = article.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var article = await dbContext.Articles.FindAsync(id);
            if (article == null)
                return NotFound();

            var model = new ArticleEditViewModel
            {
                Id = article.Id,
                Title = article.Title,
                CategoryId = article.CategoryId
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ArticleEditViewModel model)
        {
            if (ModelState.IsValid)
            {
                var article = await dbContext.Articles.FindAsync(model.Id);
                if (article == null)
                    return NotFound();

                var category = await dbContext.Categories.FindAsync(model.CategoryId);
                if (category == null)
                    return NotFound();

                article.Title = model.Title;
                article.Category = category;

                dbContext.Update(article);
                await dbContext.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var article = await dbContext.Articles
                .Include(a => a.Category)
                .Include(a => a.Author)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (article == null)
                return NotFound();

            return View(article);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var article = await dbContext.Articles.FindAsync(id);
            if (article != null)
            {
                dbContext.Articles.Remove(article);
                await dbContext.SaveChangesAsync();

ScientificEdition/Controllers/JournalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ScientificEdition.Business;
using ScientificEdition.Data;
using ScientificEdition.Data.Entities;
using ScientificEdition.Models.Journal;
using ScientificEdition.Utilities.Files;
using Syncfusion.DocIO;
using Syncfusion.DocIO.DLS;
using Syncfusion.DocIORenderer;
using System.Security.Authentication;

namespace ScientificEdition.Controllers
{
    public class JournalController : Controller
    {
        private readonly ArticleManager articleManager;
        private readonly ApplicationDbContext dbContext;
        private readonly FileManager fileManager;

        public JournalController(
            ArticleManager articleManager,
            ApplicationDbContext dbContext,
            FileManager fileManager)
        {
            this.articleManager = articleManager;
            this.dbContext = dbContext;
            this.fileManager = fileManager;
        }

        public async Task<IActionResult> Index(Guid categoryId)
        {
            var category = await dbContext.Categories
                .FirstOrDefaultAsync(c => c.Id == categoryId);

            if (category == null)
                return NotFound();

            var journals = await dbContext.JournalEditions
                .Where(j => j.CategoryId == categoryId && j.Published && j.PublishDate <= DateTime.Now)
                .Include(j => j.Articles)
                .ToListAsync();

            var model = new JournalIndexViewModel
            {
                Category = category,
                Journals = journals
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edition(Guid id)
        {
            var journal = await dbContext.JournalEditions
                .Include(j => j.Category)
                .Include(j => j.Articles)
                .ThenInclude(a => a.Author)
                .FirstOrDefaultAsync(j => j.Id == id);

            if (journal == null || !IsJournalVisible(journal))
                return NotFound();

            return View(journal);
        }

        [HttpGet]
        public async Task<IActionResult> Article(Guid id)
        {
            var article = await dbContext.Articles
                .Include(a => a.Author)
                .Include(a => a.JournalEdition)
                .FirstOrDefaultAsync(a => a.Id == id && a.Status == ArticleStatus.Published);

            if (article == null)
                return NotFound();

            var publishedVersion = articleManager.GetLastArticleVersion(id);
            if (publishedVersion == null)
                return NotFound();

            var downloadFileName = $"{article.JournalEdition?.Title}_{article.Title}_{article.Author?.FullName}.pdf";
            var fileCheckResult = ArticlePdfFileAlreadyExists(article);
            if (fileCheckResult.Exists)
                return PhysicalFile(fileCheckResult.Path, "application/pdf", downloadFileName);

            using (var docxStream = new FileStream(Path.GetFullPath(publishedVersion.FilePath), FileMode.Open, FileAccess.Read))
            using (var wordDocument = new WordDocument(docxStream, FormatType.Docx))
            using (var renderer = new DocIORenderer())
            {
                var pdfDocument = renderer.ConvertToPDF(wordDocument);

                var fileName = $"{article.Id}";
                var articleDirectoryPath = GetArticleDirectoryPath(article.AuthorId);

                var fullFilePath = fileManager.SavePdfFile(pdfDocument, fileName, articleDirectoryPath);
                if (string.IsNullOrEmpty(fullFilePath))
                    return BadRequest();

                return PhysicalFile(fullFilePath, "application/pdf", downloadFileName);
            }
        }

        private static bool IsJournalVisible(JournalEdition journal)
            => journal.Published && journal.PublishDate <= DateTime.Now;

        private (bool Exists, string Path) ArticlePdfFileAlreadyExists(Article article)
        {
            var fileNameWithExtension = $"{article.Id}.pdf";
            var articleDirectoryPath = GetArticleDirectoryPath(article.AuthorId);

            var fullFilePath = Path.Combine(fileManager.GetFullPath(articleDirectoryPath), fileNameWithExtension);
            return (System.IO.File.Exists(fullFilePath), fullFilePath);
        }

        public string[] GetArticleDirectoryPath(string authorId)
        {
            if (string.IsNullOrEmpty(authorId))
                throw new AuthenticationException();

            return ["Documents", authorId];
        }
    }
}

ScientificEdition/Views/Article/Create.cshtml
@model ArticleInputModel
@using ScientificEdition.Business
@using ScientificEdition.Models.Article
@inject CategoryManager CategoryManager

@{
    ViewData["Title"] = "Створити нову статтю";

    var categoryOptions = CategoryManager.GetAllCategories().Select(category => new SelectListItem
            {
                Text = category.Name,
                Value = category.Id.ToString()
            });
}

<div class="container mt-5 col-6">
    <h2>Створити нову статтю</h2>
    <form asp-action="Create" method="post" enctype="multipart/form-data">
        <div class="mb-3">
            <label asp-for="Title" class="form-label">Заголовок</label>
            <input asp-for="Title" class="form-control" required />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="CategoryId" class="form-label">Категорія</label>
            @Html.DropDownListFor(m => m.CategoryId, categoryOptions, "Оберіть категорію...", new { @class = "form-select" })
            <span asp-validation-for="CategoryId" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="File">Файл</label>
            <input asp-for="File" type="file" accept=".docx, .doc, .pdf" class="form-control" />
            <span asp-validation-for="File" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Comment" class="form-label">Коментар</label>
            <textarea id="editor" class="form-control" name="Comment"></textarea>
            <span asp-validation-for="Comment" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-success">Створити статтю</button>
        <a asp-controller="Article" asp-action="Index" class="btn btn-secondary">Скасувати</a>
    </form>
</div>

@section Scripts {
    <script src="~/js/tinymce/tinymce.min.js"></script>
    <script>
        tinymce.init({
            selector: '#editor',
            height: 300,
            menubar: false,
            plugins: 'lists link image code',
            toolbar: 'undo redo | styleselect | bold italic | alignleft aligncenter alignright | bullist numlist outdent indent | link image | code',
            content_css: '/css/content.css'
        });
    </script>
}

ScientificEdition/Views/Article/Delete.cshtml
@using ScientificEdition.Data
@model ScientificEdition.Data.Entities.Article

@{
    ViewData["Title"] = "Видалення";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Ви впевнені, що хочете видалити статтю?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Category)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Category!.Name)
        </dd>
        @if (User.IsInRole(UserRoles.Admin))
        {
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Comment)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Comment)
            </dd>
        }
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.UploadDate)
        </dt>
        <dd class="col-sm-10">
            @Model.UploadDate.ToString("dd.MM.yyyy")
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class="col-sm-10">
            @TextHelper.Text($"ArticleStatus_{Model.Status}")
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Видалити" class="btn btn-danger" /> |
        <a asp-action="Index">Повернутись</a>
    </form>
</div>

ScientificEdition/Views/Article/Details.cshtml
@model Article
@using ScientificEdition.Data
@using ScientificEdition.Data.Entities

@{
    ViewData["Title"] = "Стаття";
}

<div class="container mt-5">
    <h2>@Model.Title</h2>
    <p><strong>Категорія:</strong> @Model.Category!.Name</p>
    <p><strong>Дата створення:</strong> @Model.UploadDate.ToString("dd.MM.yyyy")</p>
    <p><strong>Статус:</strong> @TextHelper.Text($"ArticleStatus_{Model.Status}")</p>
    @if (!string.IsNullOrEmpty(Model.Comment))
    {
        <p><strong>Comment:</strong> @Model.Comment</p>
    }

    <h3>Версії</h3>
    <ul class="list-group mb-3">
        @foreach (var version in Model.Versions)
        {
            <li class="list-group-item">
                <a href="@Url.Action("VersionDetails", "Article", new { id = version.Id })">
                    Версія №@version.VersionNumber - @version.UploadDate.ToString("dd.MM.yyyy")
                </a>
                @if (!string.IsNullOrEmpty(version.Comment))
                {
                    <p><strong>Примітка:</strong> @version.Comment</p>
                }
            </li>
        }
    </ul>

    @if (Model.Status == ArticleStatus.Rework)
    {
        <a class="btn btn-primary" href="@Url.Action("UploadVersion", "Article", new { articleId = Model.Id })">Завантажити нову версію</a>
    }
</div>

ScientificEdition/Views/Article/Edit.cshtml
@* @model ArticleViewModel
@using ScientificEdition.Data.Entities
@using ScientificEdition.Models.Article

@{
    ViewData["Title"] = "Редагування статті";
}

<div class="container mt-5">
    <h2>Редагування статті</h2>
    <form asp-action="Edit" asp-route-id="@Model.Id" method="post">
        <div class="mb-3">
            <label asp-for="Title" class="form-label">Заголовок статті</label>
            <input asp-for="Title" class="form-control" required />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Category" class="form-label">Категорія статті</label>
            <input asp-for="Category" class="form-control" required />
            <span asp-validation-for="Category" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Comment" class="form-label">Коментар</label>
            <textarea asp-for="Comment" class="form-control wysiwyg-editor" required></textarea>
            <span asp-validation-for="Comment" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-success">Зберегти зміни</button>
        <a asp-action="Index" class="btn btn-secondary">Скасувати</a>
    </form>
</div>
 *@

ScientificEdition/Views/Article/Index.cshtml
@model List<Article>
@using ScientificEdition.Data.Entities

@{
    ViewData["Title"] = "Список статей";
}

<div class="container mt-5">
    <h2 class="text-center">Список статей</h2>
    <div class="text-end mb-3">
        <a asp-controller="Article" asp-action="Create" class="btn btn-success">Додати нову статтю</a>
    </div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Стаття</th>
                <th>Категорія</th>
                <th>Дата завантаження</th>
                <th>Статус</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var article in Model)
            {
                var lastVersion = article.Versions.MaxBy(v => v.VersionNumber);

                <tr>
                    <td>@article.Title</td>
                    <td>@article.Category!.Name</td>
                    <td>@article.UploadDate.ToString("dd.MM.yyyy")</td>
                    <td>
                        <div>
                            @TextHelper.Text($"ArticleStatus_{article.Status.ToString()}")
                        </div>
                        @if (lastVersion != null)
                        {
                            @if (lastVersion.Reviews.Count >= 2)
                            {
                                <div class="text-success d-flex align-items-center">
                                    <i class="bi bi-check-circle-fill me-2" style="font-size: 1rem;"></i>
                                    <span>Перевірено</span>
                                </div>
                            }
                            else
                            {
                                <div class="text-primary d-flex align-items-center">
                                    <i class="bi bi-hourglass-split me-2" style="font-size: 1rem;"></i>
                                    <span>Відгуків: @lastVersion.Reviews.Count із 2</span>
                                </div>
                            }
                            @if (article.JournalEdition != null && article.Status == ArticleStatus.Published)
                            {
                                <div>
                                    <a href="@Url.Action("Edition", "Journal", new { id = article.JournalEditionId })">
                                        @article.JournalEdition!.Title
                                    </a>
                                </div>
                            }
                        }
                    </td>
                    <td class="text-center">
                        <a asp-controller="Article" asp-action="Details" asp-route-id="@article.Id" class="btn btn-info btn-sm">Версії</a>
                        @if (article.Status == ArticleStatus.New)
                        {
                            <a asp-controller="Article" asp-action="Edit" asp-route-id="@article.Id" class="btn btn-info btn-sm">Редагувати</a>
                            <a asp-controller="Article" asp-action="Delete" asp-route-id="@article.Id" class="btn btn-danger btn-sm">Видалити</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

ScientificEdition/Views/Article/UploadVersion.cshtml
@model ArticleVersionInputModel
@using ScientificEdition.Models.Article

@{
    ViewData["Title"] = "Нова версія";
}

<div class="container mt-5 col-6">
    <h2>@ViewData["Title"]</h2>
    <form asp-action="UploadVersion" method="post" enctype="multipart/form-data">
        @Html.HiddenFor(m => m.ArticleId)
        <div class="mb-3">
            <label asp-for="File">Файл</label>
            <input asp-for="File" type="file" accept=".docx, .doc, .pdf" class="form-control" />
            <span asp-validation-for="File" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label asp-for="Comment" class="form-label">Примітка</label>
            <textarea id="editor" class="form-control" name="Comment"></textarea>
            <span asp-validation-for="Comment" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-primary">Завантажити</button>
        @Html.ActionLink("Назад", "Details", "Article", new { id = Model.ArticleId }, new { @class = "btn btn-secondary" })
    </form>
</div>

ScientificEdition/Views/Article/VersionDetails.cshtml
@model ArticleVersion
@using ScientificEdition.Data.Entities

@{
    ViewData["Title"] = $"Версія №{Model.VersionNumber}";

    var reviews = Model.Reviews.ToList();
}

<div class="container mt-5">
    <div>
        <h2>@Model.Article!.Title - Версія №@Model.VersionNumber</h2>
        <p><strong>Дата завантаження:</strong> @Model.UploadDate.ToString("dd/MM/yyyy")</p>

        @if (!string.IsNullOrEmpty(Model.Comment))
        {
                <p><strong>Коментар:</strong> @Html.Raw(Model.Comment)</p>
        }

        <a href="@Url.Action("DownloadVersion", "Article", new { versionId = Model.Id })" class="btn btn-success">Завантажити</a>
        <a href="@Url.Action("Details", "Article", new { id = Model.Article.Id })" class="btn btn-secondary">Повернутись до версій</a>
    </div>

    @foreach (var review in reviews)
    {
        var index = reviews.IndexOf(review) + 1;
        var cardHeaderStyle = review.Result == ReviewResult.Approved ? "alert-success" : "alert-danger";

        <div class="mt-3">
            <div class="card card-header @cardHeaderStyle">
                <span>Відгук №@index - @TextHelper.Text($"ReviewResult_{review.Result}")</span>
            </div>
            <div class="card card-body">
                @Html.Raw(review.Comment)
            </div>
        </div>
    }
</div>