ScientificEdition/Areas/Admin/Models/Journal/JournalInputModel.cs
using System.ComponentModel.DataAnnotations;

namespace ScientificEdition.Areas.Admin.Models.Journal
{
    public class JournalInputModel
    {
        public Guid Id { get; set; }

        [Required]
        public string? Title { get; set; }

        public string? Description { get; set; }

        [Required]
        public Guid CategoryId { get; set; }
    }
}

ScientificEdition/Areas/Admin/Models/Journal/JournalPublishInputModel.cs
using ScientificEdition.Data.Entities;

namespace ScientificEdition.Areas.Admin.Models.Journal
{
    public class JournalPublishInputModel
    {
        public Guid JournalId { get; set; }

        public bool PublishNow { get; set; }

        public DateTime? PublishDate { get; set; }

        public JournalEdition? Journal { get; set; }
    }
}

ScientificEdition/Models/Journal/JournalIndexViewModel.cs
using ScientificEdition.Data.Entities;

namespace ScientificEdition.Models.Journal
{
    public class JournalIndexViewModel
    {
        public required Category Category { get; set; }

        public List<JournalEdition> Journals { get; set; } = [];
    }
}

ScientificEdition/Areas/Admin/Controllers/JournalsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ScientificEdition.Areas.Admin.Models.Article;
using ScientificEdition.Areas.Admin.Models.Journal;
using ScientificEdition.Data;
using ScientificEdition.Data.Entities;

namespace ScientificEdition.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class JournalsController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public JournalsController(ApplicationDbContext dbContext)
            => this.dbContext = dbContext;

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var journals = await dbContext.JournalEditions
                .Include(j => j.Category)
                .Include(j => j.Articles)
                .ToListAsync();

            return View(journals);
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var journal = await dbContext.JournalEditions
                .Include(j => j.Category)
                .Include(j => j.Articles)
                .ThenInclude(a => a.Author)
                .FirstOrDefaultAsync(j => j.Id == id);

            if (journal == null)
                return NotFound();

            return View(journal);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(JournalInputModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var journal = new JournalEdition
            {
                Title = model.Title!,
                Description = model.Description,
                CategoryId = model.CategoryId
            };

            dbContext.JournalEditions.Add(journal);
            dbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Edit(Guid id)
        {
            var journal = dbContext.JournalEditions.FirstOrDefault(c => c.Id == id);
            if (journal == null)
                return NotFound();

            var model = new JournalInputModel
            {
                Id = journal.Id,
                CategoryId = journal.CategoryId,
                Title = journal.Title,
                Description = journal.Description
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(JournalInputModel model)
        {
            if (!ModelState.IsValid)
                return View(model);

            var journal = dbContext.JournalEditions.FirstOrDefault(c => c.Id == model.Id);
            if (journal == null)
                return NotFound();

            journal.Title = model.Title!;
            journal.Description = model.Description;

            dbContext.JournalEditions.Update(journal);
            dbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Delete(Guid id)
        {
            var journal = dbContext.JournalEditions.FirstOrDefault(c => c.Id == id);
            if (journal == null)
                return NotFound();

            dbContext.JournalEditions.Remove(journal);
            dbContext.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Publish(Guid id)
        {
            var journal = await dbContext.JournalEditions
                .Include(j => j.Category)
                .FirstOrDefaultAsync(j => j.Id == id && !j.Published);

            if (journal == null)
                return NotFound();

            var model = new JournalPublishInputModel
            {
                JournalId = journal.Id,
                Journal = journal
            };
            return PartialView("_PublishJournal", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Publish(JournalPublishInputModel model)
        {
            var journal = await dbContext.JournalEditions
                .Include(j => j.Category)
                .Include(j => j.Articles)
                .FirstOrDefaultAsync(j => j.Id == model.JournalId && !j.Published);

            if (journal == null)
                return NotFound();

            if (!ModelState.IsValid)
                return BadRequest();

            if (model.PublishNow || model.PublishDate.HasValue)
            {
                foreach (var article in journal.Articles)
                    article.Status = ArticleStatus.Published;

                journal.Published = true;
                journal.PublishDate = model.PublishDate ?? DateTime.Now;

                dbContext.JournalEditions.Update(journal);
                await dbContext.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }
    }
}

ScientificEdition/Controllers/JournalController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ScientificEdition.Business;
using ScientificEdition.Data;
using ScientificEdition.Data.Entities;
using ScientificEdition.Models.Journal;
using ScientificEdition.Utilities.Files;
using Syncfusion.DocIO;
using Syncfusion.DocIO.DLS;
using Syncfusion.DocIORenderer;
using System.Security.Authentication;

namespace ScientificEdition.Controllers
{
    public class JournalController : Controller
    {
        private readonly ArticleManager articleManager;
        private readonly ApplicationDbContext dbContext;
        private readonly FileManager fileManager;

        public JournalController(
            ArticleManager articleManager,
            ApplicationDbContext dbContext,
            FileManager fileManager)
        {
            this.articleManager = articleManager;
            this.dbContext = dbContext;
            this.fileManager = fileManager;
        }

        public async Task<IActionResult> Index(Guid categoryId)
        {
            var category = await dbContext.Categories
                .FirstOrDefaultAsync(c => c.Id == categoryId);

            if (category == null)
                return NotFound();

            var journals = await dbContext.JournalEditions
                .Where(j => j.CategoryId == categoryId && j.Published && j.PublishDate <= DateTime.Now)
                .Include(j => j.Articles)
                .ToListAsync();

            var model = new JournalIndexViewModel
            {
                Category = category,
                Journals = journals
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edition(Guid id)
        {
            var journal = await dbContext.JournalEditions
                .Include(j => j.Category)
                .Include(j => j.Articles)
                .ThenInclude(a => a.Author)
                .FirstOrDefaultAsync(j => j.Id == id);

            if (journal == null || !IsJournalVisible(journal))
                return NotFound();

            return View(journal);
        }

        [HttpGet]
        public async Task<IActionResult> Article(Guid id)
        {
            var article = await dbContext.Articles
                .Include(a => a.Author)
                .Include(a => a.JournalEdition)
                .FirstOrDefaultAsync(a => a.Id == id && a.Status == ArticleStatus.Published);

            if (article == null)
                return NotFound();

            var publishedVersion = articleManager.GetLastArticleVersion(id);
            if (publishedVersion == null)
                return NotFound();

            var downloadFileName = $"{article.JournalEdition?.Title}_{article.Title}_{article.Author?.FullName}.pdf";
            var fileCheckResult = ArticlePdfFileAlreadyExists(article);
            if (fileCheckResult.Exists)
                return PhysicalFile(fileCheckResult.Path, "application/pdf", downloadFileName);

            using (var docxStream = new FileStream(Path.GetFullPath(publishedVersion.FilePath), FileMode.Open, FileAccess.Read))
            using (var wordDocument = new WordDocument(docxStream, FormatType.Docx))
            using (var renderer = new DocIORenderer())
            {
                var pdfDocument = renderer.ConvertToPDF(wordDocument);

                var fileName = $"{article.Id}";
                var articleDirectoryPath = GetArticleDirectoryPath(article.AuthorId);

                var fullFilePath = fileManager.SavePdfFile(pdfDocument, fileName, articleDirectoryPath);
                if (string.IsNullOrEmpty(fullFilePath))
                    return BadRequest();

                return PhysicalFile(fullFilePath, "application/pdf", downloadFileName);
            }
        }

        private static bool IsJournalVisible(JournalEdition journal)
            => journal.Published && journal.PublishDate <= DateTime.Now;

        private (bool Exists, string Path) ArticlePdfFileAlreadyExists(Article article)
        {
            var fileNameWithExtension = $"{article.Id}.pdf";
            var articleDirectoryPath = GetArticleDirectoryPath(article.AuthorId);

            var fullFilePath = Path.Combine(fileManager.GetFullPath(articleDirectoryPath), fileNameWithExtension);
            return (System.IO.File.Exists(fullFilePath), fullFilePath);
        }

        public string[] GetArticleDirectoryPath(string authorId)
        {
            if (string.IsNullOrEmpty(authorId))
                throw new AuthenticationException();

            return ["Documents", authorId];
        }
    }
}

ScientificEdition/Areas/Admin/Views/Journals/Create.cshtml
@using ScientificEdition.Business
@model ScientificEdition.Areas.Admin.Models.Journal.JournalInputModel
@inject CategoryManager CategoryManager

@{
    ViewData["Title"] = "Нове видання";

    var categories = CategoryManager.GetAllCategories();
    var categoryOptions = categories.Select(category => new SelectListItem
            {
                Text = category.Name,
                Value = category.Id.ToString()
            });
}

<div class="container mt-5 col-lg-9">
    <h2>Нове видання</h2>

    <form asp-action="Create" method="post">
        <div class="mb-3">
            <label asp-for="CategoryId" class="form-label">Категорія</label>
            @Html.DropDownListFor(m => m.CategoryId, categoryOptions, "Оберіть категорію...", new { @class = "form-select" })
            <span asp-validation-for="CategoryId" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Title" class="form-label">Назва</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Description" class="form-label">Опис</label>
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Зберегти</button>
            <a class="btn btn-secondary" href="@Url.Action("Index", "Journals")">Скасувати</a>
        </div>
    </form>

    <a class="btn btn-link" href="@Url.Action("Index", "Journals")">Повернутись до списку</a>
</div>

ScientificEdition/Areas/Admin/Views/Journals/Details.cshtml
@model JournalEdition
@using ScientificEdition.Data
@using ScientificEdition.Data.Entities

@{
    ViewData["Title"] = "Видання";
}

<div class="container mt-5 col-lg-9">
    <h2>@Model.Title</h2>
    <p><strong>Категорія:</strong> @Model.Category!.Name</p>
    <p><strong>Опубліковано:</strong> @(Model.Published ? "Так" : "Ні")</p>
    <p><strong>Дата публікації:</strong> @Model.PublishDate?.ToString("dd.MM.yyyy")</p>

    <div class="mt-3">
        <h3>Статті</h3>
        <ul class="list-group">
            @foreach (var article in Model.Articles)
            {
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div>
                        <a href="@Url.Action("Details", "Articles", new { id = article.Id })">
                        @article.Title - @article.Author!.FullName - @article.UploadDate.ToString("dd.MM.yyyy")
                        </a>
                    </div>
                    <a asp-area="" asp-controller="Journal" asp-action="Article" asp-route-id="@article.Id"class="btn btn-outline-secondary btn-sm">
                        Завантажити
                    </a>
                </li>
            }
        </ul>
    </div>
</div>

ScientificEdition/Areas/Admin/Views/Journals/Edit.cshtml
@model ScientificEdition.Areas.Admin.Models.Journal.JournalInputModel

@{
    ViewData["Title"] = "Редагування видання";
}

<div class="container mt-5 col-lg-9">
    <h2>Редагувати видання: @Model.Title</h2>

    <form asp-action="Edit" method="post">
        <input hidden asp-for="Id" />
        <input hidden asp-for="CategoryId" />

        <div class="mb-3">
            <label asp-for="Title" class="form-label">Назва</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Description" class="form-label">Опис</label>
            <textarea asp-for="Description" class="form-control"></textarea>
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Зберегти зміни</button>
            <a class="btn btn-secondary" href="@Url.Action("Index", "Journals")">Скасувати</a>
        </div>
    </form>

    <a class="btn btn-link" href="@Url.Action("Index", "Journals")">Повернутись до списку</a>
</div>

ScientificEdition/Areas/Admin/Views/Journals/Index.cshtml
@model List<JournalEdition>
@using ScientificEdition.Data.Entities

@{
    ViewData["Title"] = "Список видань";
}

<div class="container mt-3">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="/Admin">Панель керування</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">Список видань</li>
        </ol>
    </nav>

    <h2 class="text-start">Список видань</h2>
    <div class="text-end mb-3">
        <a asp-controller="Journals" asp-action="Create" class="btn btn-success">Створити нове видання</a>
    </div>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Назва</th>
                <th>Категорія</th>
                <th>Кількість статей</th>
                <th>Опубліковано</th>
                <th>Дата публікації</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var journal in Model)
            {
                <tr>
                    <td>
                        @if (journal.Articles.Any())
                        {
                            <a href="@Url.Action("Details", new { id = journal.Id })">@journal.Title</a>
                        }
                        else
                        {
                            @journal.Title
                        }
                    </td>
                    <td>@journal.Category!.Name</td>
                    <td>@journal.Articles.Count</td>
                    <td>@(journal.Published ? "Так" : "Ні")</td>
                    <td>@journal.PublishDate?.ToString("dd.MM.yyyy HH:mm")</td>
                    <td class="text-center">
                        @if (journal.Articles.Any() && !journal.Published)
                        {
                            <a href="@Url.Action("Publish", new { id = journal.Id })" class="btn btn-primary btn-sm open-modal-link">Опублікувати</a>
                        }
                        <a asp-controller="Journals" asp-action="Edit" asp-route-id="@journal.Id" class="btn btn-info btn-sm">Редагувати</a>
                        @if (!journal.Articles.Any())
                        {
                            <a asp-controller="Journals" asp-action="Delete" asp-route-id="@journal.Id" class="btn btn-danger btn-sm">Видалити</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="modal fade" id="publishJournalModal" tabindex="-1" role="dialog" aria-labelledby="publishJournalModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="publishJournalModalLabel">Опублікувати журнал</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="modalContent">
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.open-modal-link').on('click', function (event) {
                event.preventDefault();

                const modalContent = $('#modalContent');
                $.ajax({
                    url: $(this).attr('href'),
                    type: 'GET',
                    success: function (response) {
                        debugger;
                        modalContent.html(response);

                        $('#publishJournalModal').modal('show');
                    },
                    error: function (response) {
                        modalContent.html('<p class="text-danger">Не вдалося завантажити дані.</p>');
                    }
                });
            });
        });
    </script>
}

ScientificEdition/Areas/Admin/Views/Journals/_PublishJournal.cshtml
@using ScientificEdition.Areas.Admin.Models.Journal
@using ScientificEdition.Business
@model JournalPublishInputModel
@inject CategoryManager CategoryManager
@inject JournalManager JournalManager

<div>
    <h5>@Model.Journal!.Title</h5>
    <p>Категорія: @Model.Journal!.Category!.Name</p>

    <form method="post" asp-action="Publish">
        <input hidden asp-for="JournalId" />

        <div class="form-group mb-3">
            <div class="form-check form-switch">
                <input class="form-check-input" type="checkbox" asp-for="PublishNow" />
                <label class="form-check-label" asp-for="PublishNow">Опублікувати зараз</label>
            </div>
        </div>

        <div class="form-group mb-3">
            <label asp-for="PublishDate" class="form-label">Дата публікації</label>
            <input asp-for="PublishDate" class="form-control" type="datetime-local" />
            <span asp-validation-for="PublishDate" class="text-danger"></span>
        </div>

        <button type="submit" class="btn btn-success">Підтвердити</button>
    </form>
</div>