ScientificEdition/Areas/Admin/Models/Article/AddArticleToJournalInputModel.cs
using System.ComponentModel.DataAnnotations;

namespace ScientificEdition.Areas.Admin.Models.Article
{
    public class AddArticleToJournalInputModel
    {
        [Required]
        public Guid ArticleId { get; set; }

        [Required]
        public Guid JournalId { get; set; }

        public required Data.Entities.Article Article { get; set; }
    }
}

ScientificEdition/Areas/Admin/Models/Article/ArticleInputModel.cs
using ScientificEdition.Data;
using System.ComponentModel.DataAnnotations;

namespace ScientificEdition.Areas.Admin.Models.Article
{
    public class ArticleInputModel
    {
        public Guid Id { get; set; }

        [Required(ErrorMessage = "Поле обов'язкове.")]
        [StringLength(200, ErrorMessage = "Заголовок не може перевищувати {1} символів.")]
        [Display(Name = "Заголовок")]
        public required string Title { get; set; }

        [Required(ErrorMessage = "Поле обов'язкове.")]
        [Display(Name = "Категорія")]
        public Guid CategoryId { get; set; }

        [Required(ErrorMessage = "Поле обов'язкове.")]
        [Display(Name = "Статус")]
        public ArticleStatus Status { get; set; }

        [Display(Name = "Коментар")]
        public string? Comment { get; set; }
    }
}

ScientificEdition/Areas/Admin/Models/Article/ReviewersAssignmentModel.cs
using ScientificEdition.Mvc.Filters.Validation;
using System.ComponentModel.DataAnnotations;

namespace ScientificEdition.Areas.Admin.Models.Article
{
    public class ReviewersAssignmentModel
    {
        [Required]
        public Guid ArticleId { get; set; }

        public Data.Entities.Article? Article { get; set; }

        [Display(Name = "Доступні рецензенти")]
        [Required]
        [NonEmptyList(2)]
        public List<string> ReviewerIds { get; set; } = [];

        public bool MoveToReview { get; set; }
    }
}

ScientificEdition/Models/Article/ArticleVersionViewModel.cs
using ScientificEdition.Data;

namespace ScientificEdition.Models.Article
{
    public class ArticleVersionViewModel
    {
        public int VersionId { get; set; }

        public int VersionNumber { get; set; }

        public ArticleStatus ArticleStatus { get; set; }

        public DateTime UploadDate { get; set; }

        public string? Comment { get; set; }
    }
}

ScientificEdition/Areas/Admin/Controllers/ArticlesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NuGet.Packaging;
using ScientificEdition.Areas.Admin.Models.Article;
using ScientificEdition.Business;
using ScientificEdition.Business.Constants;
using ScientificEdition.Data;
using ScientificEdition.Data.Entities;
using ScientificEdition.Utilities.Files;

namespace ScientificEdition.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ArticlesController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly ArticleManager articleManager;
        private readonly FileManager fileManager;
        private readonly ApplicationDbContext dbContext;

        public ArticlesController(
            UserManager<User> userManager,
            ArticleManager articleManager,
            FileManager fileManager,
            ApplicationDbContext dbContext)
        {
            this.userManager = userManager;
            this.articleManager = articleManager;
            this.fileManager = fileManager;
            this.dbContext = dbContext;
        }

        [HttpGet]
        public IActionResult Index(string? query, string? status = null, string? category = null,
            string? sortField = null, string? sortOrder = null)
        {
            var articlesQuery = dbContext.Articles
                .Include(a => a.Author)
                .Include(a => a.Category)
                .Include(a => a.JournalEdition)
                .AsQueryable();

            query = query?.Trim();
            if (!string.IsNullOrEmpty(query))
            {
                var querySegments = query.ToLower().Split(' ');
                articlesQuery = articlesQuery
                    .Where(a => querySegments.Any(q => a.Title.ToLower().Contains(q))
                        || querySegments.Any(q => a.Author!.FirstName.ToLower().Contains(q))
                        || querySegments.Any(q => a.Author!.LastName.ToLower().Contains(q)));
            }

            if (!string.IsNullOrEmpty(status))
            {
                if (Enum.TryParse<ArticleStatus>(status, out var articleStatus))
                    articlesQuery = articlesQuery.Where(a => a.Status == articleStatus);
            }

            if (!string.IsNullOrEmpty(category))
                articlesQuery = articlesQuery.Where(a => a.Category!.Name == category);

            articlesQuery = sortField switch
            {
                Sorting.Fields.Title => sortOrder == Sorting.Order.SortDescending
                    ? articlesQuery.OrderByDescending(a => a.Title)
                    : articlesQuery.OrderBy(a => a.Title),

                Sorting.Fields.UploadDate => sortOrder == Sorting.Order.SortDescending
                    ? articlesQuery.OrderByDescending(a => a.UploadDate)
                    : articlesQuery.OrderBy(a => a.UploadDate),

                _ => articlesQuery.OrderByDescending(a => a.UploadDate)
            };

            var articles = articlesQuery.ToList();
            return View(articles);
        }

        [HttpGet]
        public IActionResult Details(Guid id)
        {
            var article = dbContext.Articles
                .Include(a => a.Author)
                .Include(a => a.Category)
                .Include(a => a.Versions)
                .Include(a => a.Reviewers)
                .FirstOrDefault(m => m.Id == id);

            if (article == null)
                return NotFound();

            article.Versions = article.Versions
                .OrderByDescending(v => v.UploadDate)
                .ToList();

            return View(article);
        }

        [HttpGet]
        public IActionResult VersionDetails(Guid id)
        {
            var version = dbContext.ArticleVersions
                .Include(v => v.Article)
                .Include(v => v.Reviews)
                .ThenInclude(r => r.Reviewer)
                .FirstOrDefault(v => v.Id == id);

            if (version == null)
                return NotFound();

            return View(version);
        }

        [HttpGet]
        public IActionResult DownloadVersion(Guid versionId)
        {
            var version = dbContext.ArticleVersions
                .Include(v => v.Article)
                .ThenInclude(a => a!.Author)
                .FirstOrDefault(v => v.Id == versionId);

            if (version == null)
                return NotFound();

            var filePath = version.FilePath;
            if (!System.IO.File.Exists(filePath))
                return NotFound();

            var author = version.Article!.Author;
            var authorDownloadingName = $"{author!.LastName}-{author.FirstName}";

            var articleVersionTitle = $"{authorDownloadingName}_{version.Article!.Title}_v{version.VersionNumber}";
            var downloadFileName = $"{articleVersionTitle}{Path.GetExtension(filePath)}";

            return PhysicalFile(filePath, "application/octet-stream", downloadFileName);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var article = await dbContext.Articles.FindAsync(id);
            if (article == null)
                return NotFound();

            var model = new ArticleInputModel
            {
                Id = article.Id,
                Title = article.Title,
                CategoryId = article.CategoryId,
                Status = article.Status
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ArticleInputModel model)
        {
            if (ModelState.IsValid)
            {
                var article = await dbContext.Articles.FindAsync(model.Id);
                if (article == null)
                    return NotFound();

                var category = await dbContext.Categories.FindAsync(model.CategoryId);
                if (category == null)
                    return NotFound();

                article.Title = model.Title;
                article.Category = category;
                article.Status = model.Status;

                dbContext.Update(article);
                await dbContext.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult AssignReviewers(Guid articleId)
        {
            var article = articleManager.GetArticle(articleId);
            if (article == null)
                return NotFound();
            if (article.Status != ArticleStatus.New && article.Status != ArticleStatus.Review)
                return NotFound();

            var assignedReviewers = article.Reviewers.Select(r => r.Id).ToList();
            var model = new ReviewersAssignmentModel
            {
                ArticleId = articleId,
                Article = article,
                ReviewerIds = assignedReviewers
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignReviewers(ReviewersAssignmentModel model)
        {
            var article = articleManager.GetArticle(model.ArticleId);
            if (article == null)
                return NotFound();
            if (article.Status != ArticleStatus.New && article.Status != ArticleStatus.Review)
                return NotFound();

            if (!ModelState.IsValid)
            {
                model.Article = article;
                return View(model);
            }

            if (model.ReviewerIds.Count > 2)
            {
                ModelState.AddModelError(nameof(ReviewersAssignmentModel.ReviewerIds), "Потрібно обрати 2 рецензенти.");
                model.Article = article;
                return View(model);
            }

            var selectedUsers = dbContext.Users.Where(u => model.ReviewerIds.Contains(u.Id)).ToList();
            var validReviewers = new List<User>();
            foreach (var user in selectedUsers)
            {
                if (user != null && await userManager.IsInRoleAsync(user, UserRoles.Reviewer))
                    validReviewers.Add(user);
            }

            if (validReviewers.Count < 2)
            {
                ModelState.AddModelError(nameof(ReviewersAssignmentModel.ReviewerIds), "Деякі рецензенти недоступні для вибору.");

                model.ReviewerIds = validReviewers.Select(r => r.Id).ToList();
                return View(model);
            }

            article.Reviewers.Clear();
            article.Reviewers.AddRange(validReviewers);

            if (model.MoveToReview)
                article.Status = ArticleStatus.Review;

            await dbContext.SaveChangesAsync();

            return RedirectToAction(nameof(Details), new { id = article.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var article = await dbContext.Articles
                .Include(a => a.Category)
                .Include(a => a.Author)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (article == null)
                return NotFound();

            return View(article);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var article = await dbContext.Articles
                .FirstOrDefaultAsync(a => a.Id == id);

            if (article != null)
            {
                dbContext.Articles.Remove(article);
                await dbContext.SaveChangesAsync();

                var articleDirectoryPath = GetArticleDirectoryPath(article.Id, article.AuthorId);
                fileManager.DeleteDirectory(articleDirectoryPath);
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]

ScientificEdition/Areas/Admin/Controllers/UsersController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ScientificEdition.Areas.Admin.Models.Users;
using ScientificEdition.Data;
using ScientificEdition.Data.Entities;

namespace ScientificEdition.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class UsersController : Controller
    {
        private readonly UserManager<User> userManager;
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly ApplicationDbContext dbContext;

        public UsersController(
            UserManager<User> userManager,
            RoleManager<IdentityRole> roleManager,
            ApplicationDbContext dbContext)
        {
            this.userManager = userManager;
            this.roleManager = roleManager;
            this.dbContext = dbContext;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string role)
        {
            if (string.IsNullOrWhiteSpace(role))
                return NotFound();

            var roleExists = await roleManager.RoleExistsAsync(role);
            if (!roleExists)
                return NotFound($"Role '{role}' does not exist.");

            var users = await userManager.GetUsersInRoleAsync(role);

            if (role == UserRoles.Reviewer)
            {
                var allCategories = await dbContext.Categories.Include(c => c.Users).ToListAsync();
                foreach (var user in users)
                    user.Categories = allCategories.Where(c => c.Users.Any(u => u.Id == user.Id)).ToList();
            }

            var model = new UsersListViewModel
            {
                Role = role,
                Users = users
            };

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var user = await dbContext.Users
                .Include(u => u.Categories)
                .FirstOrDefaultAsync(u => u.Id == id);

            if (user == null)
                return NotFound();

            var role = await GetUserRoleName(user);
            var model = new UserUpdateInputModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email!,
                Role = role,
                CategoryIds = role == UserRoles.Reviewer ? user.Categories.Select(c => c.Id).ToList() : []
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, UserUpdateInputModel model)
        {
            if (id != model.Id)
                return NotFound();

            if (!ModelState.IsValid)
                return View(model);

            if (model.Role == UserRoles.Reviewer && model.CategoryIds.Count == 0)
                return View(model);

            var user = await dbContext.Users
                .Include(u => u.Categories)
                .FirstOrDefaultAsync(u => u.Id == id);

            if (user == null)
                return NotFound();

            user.FirstName = model.FirstName;
            user.LastName = model.LastName;
            user.UserName = model.Email;
            user.Email = model.Email;

            var result = await userManager.UpdateAsync(user);
            if (result.Succeeded)
            {
                var role = await GetUserRoleName(user);
                if (model.Role != role)
                {
                    var userRoles = await userManager.GetRolesAsync(user);
                    await userManager.RemoveFromRolesAsync(user, userRoles);
                    await userManager.AddToRoleAsync(user, model.Role!);
                }

                if (model.Role == UserRoles.Reviewer)
                {
                    user.Categories.Clear();

                    var categories = await dbContext.Categories.Where(c => model.CategoryIds.Contains(c.Id)).ToListAsync();
                    user.Categories = categories;

                    await dbContext.SaveChangesAsync();
                }

                return RedirectToAction(nameof(Index), new { role = model.Role });
            }

            return View(model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();

            var role = await GetUserRoleName(user);
            return View((user, role));
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var user = await userManager.FindByIdAsync(id);
            if (user == null)
                return NotFound();

            var role = await GetUserRoleName(user);

            var result = await userManager.DeleteAsync(user);
            if (result.Succeeded)
                return RedirectToAction(nameof(Index), new { role });

            return View((user, role));
        }

        private async Task<string?> GetUserRoleName(User user)
        {
            if (user == null)
                return string.Empty;

            var roles = await userManager.GetRolesAsync(user);
            return roles.FirstOrDefault();
        }
    }
}

ScientificEdition/Areas/Admin/Views/Articles/Details.cshtml
@model Article
@using ScientificEdition.Data
@using ScientificEdition.Data.Entities

@{
    ViewData["Title"] = "Стаття";
}

<div class="container mt-5 col-lg-9">
    <h2>@Model.Title</h2>
    <p><strong>Автор:</strong> @Model.Author!.FullName</p>
    <p><strong>Категорія:</strong> @Model.Category!.Name</p>
    <p><strong>Дата створення:</strong> @Model.UploadDate.ToString("dd.MM.yyyy")</p>
    <p><strong>Статус:</strong> @TextHelper.Text($"ArticleStatus_{Model.Status}")</p>
    @if (!string.IsNullOrEmpty(Model.Comment))
    {
        <p><strong>Коментар:</strong> @Model.Comment</p>
    }

    <h3>Версії</h3>
    <ul class="list-group mb-3">
        @foreach (var version in Model.Versions)
        {
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <div>
                    <a href="@Url.Action("VersionDetails", "Articles", new { id = version.Id })">
                        Версія №@version.VersionNumber - @version.UploadDate.ToString("dd.MM.yyyy")
                    </a>
                    @if (!string.IsNullOrEmpty(version.Comment))
                    {
                        <p><strong>Примітка:</strong> @version.Comment</p>
                    }
                </div>
                <a class="btn btn-outline-secondary btn-sm" href="@Url.Action("DownloadVersion", "Articles", new { versionId = version.Id })">
                    Завантажити
                </a>
            </li>
        }
    </ul>

    @if (Model.Reviewers.Any())
    {
        <h3>Рецензенти</h3>
        <ul class="list-group">
            @foreach (var reviewer in Model.Reviewers)
            {
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <div>
                        <a href="@Url.Action("Edit", "Users", new { id = reviewer.Id })">
                            @reviewer.FullName
                        </a>
                    </div>
                </li>
            }
        </ul>
    }

    <div class="mt-4">
        <a class="btn btn-info" href="@Url.Action("Edit", "Articles", new { id = Model.Id })">Редагувати статтю</a>
        @if (Model.Status == ArticleStatus.New)
        {
            <a class="btn btn-primary" href="@Url.Action("AssignReviewers", "Articles", new { articleId = Model.Id })">Призначити рецензентів</a>
        }
        else if (Model.Status == ArticleStatus.Review)
        {
            <a class="btn btn-primary" href="@Url.Action("AssignReviewers", "Articles", new { articleId = Model.Id })">Змінити рецензентів</a>
        }
    </div>
</div>

ScientificEdition/Areas/Admin/Views/Articles/Edit.cshtml
@model ScientificEdition.Areas.Admin.Models.Article.ArticleInputModel
@using ScientificEdition.Business
@using ScientificEdition.Data
@using ScientificEdition.Data.Entities
@inject CategoryManager CategoryManager

@{
    ViewData["Title"] = "Редагування статті";

    var categories = CategoryManager.GetAllCategories();
    var categoryOptions = categories.Select(category => new SelectListItem
            {
                Text = category.Name,
                Value = category.Id.ToString()
            });

    var statuses = Enum.GetValues(typeof(ArticleStatus)) as IEnumerable<ArticleStatus>;
    var statusOptions = statuses!.Select(status => new SelectListItem
            {
                Text = TextHelper.Text($"ArticleStatus_{status}"),
                Value = status.ToString()
            });
}

<div class="container mt-5 col-lg-9">
    <h2>Редагувати статтю: @Model.Title</h2>

    <form asp-action="Edit" method="post">
        <div class="mb-3">
            <label asp-for="Title" class="form-label">Заголовок</label>
            <input asp-for="Title" class="form-control" />
            <span asp-validation-for="Title" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <label asp-for="CategoryId" class="form-label">Категорія</label>
            @Html.DropDownListFor(m => m.CategoryId, categoryOptions, "Оберіть категорію...", new { @class = "form-select" })
            <span asp-validation-for="CategoryId"></span>
        </div>

        <div class="mb-3">
            <label asp-for="Status" class="form-label">Статус</label>
            @Html.DropDownListFor(m => m.Status, statusOptions, new { @class = "form-select" })
            <span asp-validation-for="Status" class="text-danger"></span>
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary">Зберегти зміни</button>
            <a class="btn btn-secondary" href="@Url.Action("Details", "Articles", new { id = Model.Id })">Скасувати</a>
        </div>
    </form>

    <a class="btn btn-link" href="@Url.Action("Index", "Articles")">Повернутись до списку</a>
</div>

ScientificEdition/Areas/Admin/Views/Articles/Index.cshtml
@model List<Article>
@using ScientificEdition.Business
@using ScientificEdition.Data
@using ScientificEdition.Data.Entities
@using Microsoft.AspNetCore.Http
@inject CategoryManager CategoryManager

@{
    ViewData["Title"] = "Список статей";
}

<div class="container mt-5">
    <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="/Admin">Панель керування</a>
            </li>
            <li class="breadcrumb-item active" aria-current="page">
                <a href="@Url.Action("Index")">Список статей</a>
            </li>
        </ol>
    </nav>

    <form method="get" class="mb-4">
        <div class="row">
            <div class="col-md-3">
                <label for="query" class="form-label">Пошук:</label>
                <input type="text" name="query" id="query" class="form-control" value="@Context.Request.Query["query"]" placeholder="Назва або автор..." />
            </div>

            <div class="col-md-2">
                <label for="status" class="form-label">Статус:</label>
                <select name="status" id="status" class="form-select">
                    <option value="">Всі</option>
                    @foreach (var status in Enum.GetValues<ArticleStatus>())
                    {
                        <option value="@status" selected="@(Context.Request.Query["status"] == status.ToString())">
                            @TextHelper.Text($"ArticleStatus_{status}")
                        </option>
                    }
                </select>
            </div>

            <div class="col-md-2">
                <label for="category" class="form-label">Категорія:</label>
                <select name="category" id="category" class="form-select">
                    <option value="">Всі</option>
                    @foreach (var category in CategoryManager.GetAllCategories())
                    {
                        <option value="@category.Name" selected="@(Context.Request.Query["category"] == category.Name)">
                            @category.Name
                        </option>
                    }
                </select>
            </div>

            <div class="col-md-2 align-self-end">
                <button type="submit" class="btn btn-primary">Фільтрувати</button>
            </div>
        </div>
    </form>

    <div class="mb-2">
        Сортувати за:
        <a href="@GetUpdatedSortingQueryString("sortField", "Title")" class="btn btn-link">Назва ↑</a>
        <a href="@GetUpdatedSortingQueryString("sortField", "Title", false)" class="btn btn-link">Назва ↓</a>
        <a href="@GetUpdatedSortingQueryString("sortField", "UploadDate")" class="btn btn-link">Дата ↑</a>
        <a href="@GetUpdatedSortingQueryString("sortField", "UploadDate", false)" class="btn btn-link">Дата ↓</a>
    </div>

    <h2 class="">Список статей</h2>
    <table class="table table-striped table-hover">
        <thead>
            <tr>
                <th>Стаття</th>
                <th>Категорія</th>
                <th>Автор</th>
                <th>Дата завантаження</th>
                <th>Статус</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var article in Model)
            {
                var author = article.Author!;
                <tr>
                    <td>
                        <a asp-controller="Articles" asp-action="Details" asp-route-id="@article.Id">@article.Title</a>
                    </td>
                    <td>@article.Category!.Name</td>
                    <td>
                        <a asp-controller="Users" asp-action="Edit" asp-route-id="@author.Id">@author.FullName</a>
                    </td>
                    <td>@article.UploadDate.ToString("dd.MM.yyyy")</td>
                    <td>
                        <div>
                            @TextHelper.Text($"ArticleStatus_{article.Status.ToString()}")
                        </div>
                        @if (article.JournalEdition != null && (article.Status == ArticleStatus.Scheduled || article.Status == ArticleStatus.Published))
                        {
                            <a href="@Url.Action("Details", "Journals", new { id = article.JournalEditionId })">
                                @article.JournalEdition!.Title
                            </a>
                        }
                    </td>
                    <td class="text-center">
                        @if (article.Status == ArticleStatus.Approved)
                        {
                            <a href="@Url.Action("AddToJournal", new { articleId = article.Id })" class="btn btn-primary btn-sm open-modal-link">Запланувати</a>
                        }
                        <a asp-controller="Articles" asp-action="Details" asp-route-id="@article.Id" class="btn btn-info btn-sm">Деталі</a>
                        @if (article.Status != ArticleStatus.Scheduled && article.Status != ArticleStatus.Published)
                        {
                            <a asp-controller="Articles" asp-action="Delete" asp-route-id="@article.Id" class="btn btn-danger btn-sm">Видалити</a>
                        }
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
<div class="modal fade" id="addToJournalModal" tabindex="-1" role="dialog" aria-labelledby="addToJournalModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="addToJournalModalLabel">Опублікувати статтю</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="modalContent">
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            $('.open-modal-link').on('click', function (event) {
                event.preventDefault();

                const modalContent = $('#modalContent');
                $.ajax({
                    url: $(this).attr('href'),
                    type: 'GET',
                    success: function (response) {
                        modalContent.html(response);

                        $('#addToJournalModal').modal('show');
                    },
                    error: function () {
                        modalContent.html('<p class="text-danger">Не вдалося завантажити дані.</p>');
                    }
                });
            });
        });
    </script>
}

@functions {
    string GetUpdatedSortingQueryString(string field, string value, bool ascending = true)
    {
        var query = Context.Request.Query.ToDictionary(x => x.Key, x => x.Value.ToString());

        query[field] = value;
        query["sortOrder"] = ascending ? "asc" : "desc";

        return "?" + string.Join("&", query.Select(kvp => $"{kvp.Key}={Uri.EscapeDataString(kvp.Value)}"));
    }
}

ScientificEdition/Areas/Admin/Views/Articles/VersionDetails.cshtml
@model ArticleVersion
@using ScientificEdition.Data
@using ScientificEdition.Data.Entities

@{
    ViewData["Title"] = $"Версія №{Model.VersionNumber}";

    var reviews = Model.Reviews.ToList();
}

<div class="container mt-5">
    <h2>@Model.Article!.Title - Версія №@Model.VersionNumber</h2>
    <p><strong>Дата завантаження:</strong> @Model.UploadDate.ToString("dd/MM/yyyy")</p>

    @if (!string.IsNullOrEmpty(Model.Comment))
    {
        <p><strong>Коментар:</strong> @Html.Raw(Model.Comment)</p>
    }

    <a href="@Url.Action("DownloadVersion", "Articles", new { versionId = Model.Id })" class="btn btn-success">Завантажити</a>
    <a href="@Url.Action("Details", "Articles", new { id = Model.Article.Id })" class="btn btn-secondary">Повернутись до статтей</a>

    @foreach (var review in reviews)
    {
        var index = reviews.IndexOf(review) + 1;
        var cardHeaderStyle = review.Result == ReviewResult.Approved ? "alert-success" : "alert-danger";

        <div class="mt-3">
            <div class="card card-header @cardHeaderStyle">
                <div>@review.Reviewer!.FullName - <b>@TextHelper.Text($"ReviewResult_{review.Result}")</b></div>
                <div class="small">Дата перевірки: @review.ReviewDate.ToString("dd.MM.yyyy")</div>
            </div>
            <div class="card card-body">
                @Html.Raw(review.Comment)
            </div>
        </div>
    }
</div>